
#configuración tomcat
server.port: 8095

#spring security custom password
spring.security.user.password = demo@123

# Configuración de BD H2 y JPA                  
spring.datasource.url: jdbc:h2:file:~/data/sportcafe;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username: root
spring.datasource.password: root


spring.jpa.hibernate.ddl-auto: update

allowed.origin=http://localhost:


# Le decimos a Spring Boot que tome el puerto que Render le asigne, 
# o que use el 8080 por defecto si lo corres en tu PC.
server.port=${PORT:8080}

# ESTO ES LA CLAVE: Le decimos a Tomcat que escuche en todas las 
# interfaces de red del contenedor Docker, no solo en "localhost".
server.address=0.0.0.0
