

#spring security custom password
spring.security.user.password = demo@123

# Configuración de BD H2 y JPA                  
# spring.datasource.url: jdbc:h2:file:~/data/sportcafe;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.username: root
# spring.datasource.password: root


# Si la variable DB_URL no existe, usa localhost por defecto.
# Si existe, usará la URL de producción.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tu_base_local}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}


# Configuración de Cloudinary usando variables de entorno para mayor seguridad en Render
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:local}
cloudinary.api_key=${CLOUDINARY_API_KEY:local}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:local}

# Hibernate: update crea/actualiza las tablas automáticamente según los @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

allowed.origin=http://localhost:


# Le decimos a Spring Boot que tome el puerto que Render le asigne, 
# o que use el 8080 por defecto si lo corres en tu PC.
server.port=${PORT:8080}

# ESTO ES LA CLAVE: Le decimos a Tomcat que escuche en todas las 
# interfaces de red del contenedor Docker, no solo en "localhost".
server.address=0.0.0.0
